name: CI Pipeline

on:
  pull_request:
    types:
      - opened  # Runs CI when a PR is created
      - synchronize  # Runs CI when new commits are pushed to an open PR

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        working-directory: my-node-app  # ✅ Change to correct directory
        run: npm install

      - name: Run Linting
        working-directory: my-node-app
        run: npm run lint || true

      - name: Run Unit Tests
        working-directory: my-node-app
        run: npm test || true

      - name: Run Security Scan
        working-directory: my-node-app
        run: npm audit --audit-level=critical || true
